### ISSUE TITLE
Feature request: Repeating content fields

### ISSUE THREAD

**Issue by martonlente** [vapid/vapid#94] opened 2018-11-11 14:03 UTC
Hello,

I've started using Vapid, and I'm truly amazed by its ease of use and flexibility. However, there is one feature I really miss, that may add even more flexibility without adding too much complexity to the system.

**You can now add all kinds of repeating content by using sections, with `multiple` attribute set to `true`. This can also be used to create a blog-like, or 'list/detail' page functionality. However, there is currently no way to add repeating content within individual 'blog items' or 'detail pages'.** To better describe – let's say, I'd like to create a blog, where blog posts may have an image gallery, with varying number of images. As a workaround I could set up multiple image-type content fields, and simply use only as many as I need to upload images when managing content. However, **it'd be much more elegant, to simply enabling repeating content within sections, maybe by adding an attribute or so.**

To illustrate this, I may reference Perch CMS, that has 'Repeaters tags' – sorry for the comparision, but that's  good example, to get the idea. This could be used to repeat list items, images, etc. A similar functionality would be very welcome to Vapid too, and open up a lot of possibilities!

Kind regards,
Márton Lente

**Comment by walidvb** [comment] 2018-11-11 19:55
dupe of #6 , which was closed for the benefit of #57. Feel free to participate there, so we can move all this forward! :)

**Comment by walidvb** [comment] 2018-11-12 10:53
Agree on the 'core' part. I think @srobbin was weary of adding this already, as it might impact the architecture of the way input is handled.

Not sure what you mean by 8 content types instead of seven? as far as i understand, each content type would need to be storable as unique value _or_ array, no?

**Comment by martonlente** [comment] 2018-11-12 11:40
Thanks @walidvb for your answer. Regarding the 'eighth content type' I wrote, I meant it could be implemented as a new content type. Maybe I was wrong, as its syntax could be more similar to sections'.

What I mean could work (or look) like this in code:
```
{{#section about}}
<div>
  <h2>{{title}}</h2>
  <ul>
    {{#repeat}}
      <li>
        <h5>{{school}}</h5>
        {{city}}, {{state}}
      </li>
    {{/repeat}}
  </ul>
</div>
{{/section}}
```

I think the above would be very familiar to Vapids' logic, and wouldn't overshadow its simplicity. A repeater shouldn't even have a name necessarily. Or it could be implemented by using a section, without naming it, but adding multiple attribute set to true.

I'm also aware of the suggestion regarding nested sections, which I also find useful, but definitely see as a different feature, not a 'replacement' to this.

Kind regards,
Márton Lente

**Comment by srobbin** [comment] 2018-11-15 20:17
@martonlente Thanks for the suggestion. I think this close enough to being a Duplicate of #6 that I'd like to consolidate the conversations, but we'll definitely take your `#repeat` idea into consideration.

**Closed by srobbin** 2018-11-15 20:17 UTC
Labels: duplicate
