### ISSUE TITLE
Error when running vapid start

### ISSUE THREAD

**Issue by tobiasger** [vapid/vapid#121] opened 2019-03-06 18:32 UTC
**Describe the issue**
I'm getting an error right after running `vapid start <project-name>`. `vapid new <project-name>` is working like it should. I haven't made any changes to the files of the Vapid installation. I can run the `vapid start` command and everything seems fine, but when I visit `localhost:3000` through any browser, the following error pops up in the terminal:

```
GET / 200 6437 - 260.998 ms [GA1.1.322119533.1548941910]
(node:15125) UnhandledPromiseRejectionWarning: TypeError: res.getHeader is not a function
    at processRequest (/usr/local/lib/node_modules/vapid-cli/node_modules/webpack-dev-middleware/lib/middleware.js:82:18)
    at ready (/usr/local/lib/node_modules/vapid-cli/node_modules/webpack-dev-middleware/lib/util.js:51:12)
    at handleRequest (/usr/local/lib/node_modules/vapid-cli/node_modules/webpack-dev-middleware/lib/util.js:167:5)
    at Promise (/usr/local/lib/node_modules/vapid-cli/node_modules/webpack-dev-middleware/lib/middleware.js:44:7)
    at new Promise (<anonymous>)
    at middleware (/usr/local/lib/node_modules/vapid-cli/node_modules/webpack-dev-middleware/lib/middleware.js:43:12)
    at Promise.all.Promise (/usr/local/lib/node_modules/vapid-cli/node_modules/koa-webpack/index.js:43:7)
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/vapid-cli/node_modules/koa-webpack/index.js:42:5
    at dispatch (/usr/local/lib/node_modules/vapid-cli/node_modules/koa-compose/index.js:42:32)
    at session (/usr/local/lib/node_modules/vapid-cli/node_modules/koa-session/index.js:41:13)
    at dispatch (/usr/local/lib/node_modules/vapid-cli/node_modules/koa-compose/index.js:42:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:15125) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15125) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:15125) UnhandledPromiseRejectionWarning: TypeError: res.getHeader is not a function
    at processRequest (/usr/local/lib/node_modules/vapid-cli/node_modules/webpack-dev-middleware/lib/middleware.js:82:18)
    at ready (/usr/local/lib/node_modules/vapid-cli/node_modules/webpack-dev-middleware/lib/util.js:51:12)
    at handleRequest (/usr/local/lib/node_modules/vapid-cli/node_modules/webpack-dev-middleware/lib/util.js:167:5)
    at Promise (/usr/local/lib/node_modules/vapid-cli/node_modules/webpack-dev-middleware/lib/middleware.js:44:7)
    at new Promise (<anonymous>)
    at middleware (/usr/local/lib/node_modules/vapid-cli/node_modules/webpack-dev-middleware/lib/middleware.js:43:12)
    at Promise.all.Promise (/usr/local/lib/node_modules/vapid-cli/node_modules/koa-webpack/index.js:43:7)
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/vapid-cli/node_modules/koa-webpack/index.js:42:5
    at dispatch (/usr/local/lib/node_modules/vapid-cli/node_modules/koa-compose/index.js:42:32)
    at session (/usr/local/lib/node_modules/vapid-cli/node_modules/koa-session/index.js:41:13)
    at dispatch (/usr/local/lib/node_modules/vapid-cli/node_modules/koa-compose/index.js:42:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:15125) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
GET /%7B%7Bbackground_image%7D%7D 404 1811 - 11.707 ms [GA1.1.322119533.1548941910]
(node:15125) UnhandledPromiseRejectionWarning: TypeError: res.getHeader is not a function
    at processRequest (/usr/local/lib/node_modules/vapid-cli/node_modules/webpack-dev-middleware/lib/middleware.js:82:18)
    at ready (/usr/local/lib/node_modules/vapid-cli/node_modules/webpack-dev-middleware/lib/util.js:51:12)
    at handleRequest (/usr/local/lib/node_modules/vapid-cli/node_modules/webpack-dev-middleware/lib/util.js:167:5)
    at Promise (/usr/local/lib/node_modules/vapid-cli/node_modules/webpack-dev-middleware/lib/middleware.js:44:7)
    at new Promise (<anonymous>)
    at middleware (/usr/local/lib/node_modules/vapid-cli/node_modules/webpack-dev-middleware/lib/middleware.js:43:12)
    at Promise.all.Promise (/usr/local/lib/node_modules/vapid-cli/node_modules/koa-webpack/index.js:43:7)
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/vapid-cli/node_modules/koa-webpack/index.js:42:5
    at dispatch (/usr/local/lib/node_modules/vapid-cli/node_modules/koa-compose/index.js:42:32)
    at session (/usr/local/lib/node_modules/vapid-cli/node_modules/koa-session/index.js:41:13)
    at dispatch (/usr/local/lib/node_modules/vapid-cli/node_modules/koa-compose/index.js:42:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:15125) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

And nothing is visible in the browser tab showing the `localhost:3000` site. When I cancel the process in the terminal, the site is shown, but just as raw markup. So I can see the curly brackets on *Hello, {{vapid}}*. Not sure if this is a bug with the CLI or if there's something else causing this.

**Your Environment**
 - OS: OS X 10.13.6
 - Browser: –
 - Node Version: v10.11.0
 - Vapid Version: 0.3.5

**Comment by stepjkl** [comment] 2019-03-07 01:24
Hi there,

I am having the _same exact issue_. I wanted to try Vapid for the first time and this came out in the terminal instead (the localhost page keeps loading):

```
==> Starting the development server...
==> Watching for changes in (project folder)
View your website at http://localhost:3000
Ctrl + C to quit
(node:84710) UnhandledPromiseRejectionWarning: TypeError: res.getHeader is not a function
    at processRequest (/usr/local/lib/node_modules/@vapid/cli/node_modules/webpack-dev-middleware/lib/middleware.js:82:18)
    at ready (/usr/local/lib/node_modules/@vapid/cli/node_modules/webpack-dev-middleware/lib/util.js:51:12)
    at handleRequest (/usr/local/lib/node_modules/@vapid/cli/node_modules/webpack-dev-middleware/lib/util.js:167:5)
    at Promise (/usr/local/lib/node_modules/@vapid/cli/node_modules/webpack-dev-middleware/lib/middleware.js:44:7)
    at new Promise (<anonymous>)
    at middleware (/usr/local/lib/node_modules/@vapid/cli/node_modules/webpack-dev-middleware/lib/middleware.js:43:12)
    at Promise.all.Promise (/usr/local/lib/node_modules/@vapid/cli/node_modules/koa-webpack/index.js:43:7)
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/@vapid/cli/node_modules/koa-webpack/index.js:42:5
    at dispatch (/usr/local/lib/node_modules/@vapid/cli/node_modules/koa-compose/index.js:42:32)
    at session (/usr/local/lib/node_modules/@vapid/cli/node_modules/koa-session/index.js:41:13)
    at dispatch (/usr/local/lib/node_modules/@vapid/cli/node_modules/koa-compose/index.js:42:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:84710) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:84710) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:84710) UnhandledPromiseRejectionWarning: TypeError: res.getHeader is not a function
    at processRequest (/usr/local/lib/node_modules/@vapid/cli/node_modules/webpack-dev-middleware/lib/middleware.js:82:18)
    at ready (/usr/local/lib/node_modules/@vapid/cli/node_modules/webpack-dev-middleware/lib/util.js:51:12)
    at handleRequest (/usr/local/lib/node_modules/@vapid/cli/node_modules/webpack-dev-middleware/lib/util.js:167:5)
    at Promise (/usr/local/lib/node_modules/@vapid/cli/node_modules/webpack-dev-middleware/lib/middleware.js:44:7)
    at new Promise (<anonymous>)
    at middleware (/usr/local/lib/node_modules/@vapid/cli/node_modules/webpack-dev-middleware/lib/middleware.js:43:12)
    at Promise.all.Promise (/usr/local/lib/node_modules/@vapid/cli/node_modules/koa-webpack/index.js:43:7)
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/@vapid/cli/node_modules/koa-webpack/index.js:42:5
    at dispatch (/usr/local/lib/node_modules/@vapid/cli/node_modules/koa-compose/index.js:42:32)
    at session (/usr/local/lib/node_modules/@vapid/cli/node_modules/koa-session/index.js:41:13)
    at dispatch (/usr/local/lib/node_modules/@vapid/cli/node_modules/koa-compose/index.js:42:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:84710) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
GET / 200 6437 - 94.500 ms [-]
```

Also, I reinstalled all the global packages including vapid, node.js and npm which are most likely to be the cause from what I researched.

Thank you!

OS X 10.13.6
@vapid/cli: 0.7.3
node: 10.15.3
npm: 6.4.1

**Comment by tobiasger** [comment] 2019-03-07 09:47
> Also, I reinstalled all the global packages including vapid, node.js and npm which are most likely to be the cause from what I researched.
Did it work after this or was there no difference?

**Comment by stepjkl** [comment] 2019-03-07 09:54
@tobiasger Nope, I still get the same error(s).

**Comment by tobiasger** [comment] 2019-03-07 11:39
Sorry for doing duplicates, but I read somewhere that errors should be posted in the Vapid Forum, so I did [a post there as well](https://forums.vapid.com/t/error-when-running-vapid-start/211). Whichever posts that the maintainers prefer to be closed can be closed.

**Comment by srobbin** [comment] 2019-03-07 14:48
Looks like it's [an issue](https://github.com/shellscape/koa-webpack/issues/109) with one of our dependencies. Thankfully, there's [a pull request](https://github.com/shellscape/koa-webpack/pull/110) ready that should fix the problem.

If the PR doesn't get merged today, I'll look into a temp fix.

**Comment by srobbin** [comment] 2019-03-07 19:45
I think I found a decent, temporary workaround, at least until that PR is resolved. Try installing the latest version of Vapid (0.7.4), and let me know if that fixes the problem.

To update:
`npm install -g @vapid/cli`

**Comment by tobiasger** [comment] 2019-03-07 20:55
Thank you! Updating Vapid fixed it for me. I had a very old version anyways, so I should've just tried that first.

**Comment by stepjkl** [comment] 2019-03-07 23:06
It is working now, thank you!

**Closed** 2019-03-08 01:23 UTC

**Comment by srobbin** [comment] 2019-03-08 01:25
@tobiasger The other versions would’ve been broken too. 😉

Thanks so much for submitting this issue.
